#define HTML_BREAK			        "<br>"
#define HTML_HORIZONTAL_LINE        "<hr>"

#define HTML_M_START_HEADER_1       "<h1 id=\""
#define HTML_M_START_HEADER_2       "<h2 id=\""
#define HTML_M_START_HEADER_3       "<h3 id=\""
#define HTML_M_START_HEADER_4       "<h4 id=\""
#define HTML_M_START_HEADER_5       "<h5 id=\""
#define HTML_M_START_HEADER_6       "<h6 id=\""

#define HTML_M_MID                  "\">"

#define HTML_M_END_HEADER_1         "</h1>"
#define HTML_M_END_HEADER_2         "</h2>"
#define HTML_M_END_HEADER_3         "</h3>"
#define HTML_M_END_HEADER_4         "</h4>"
#define HTML_M_END_HEADER_5         "</h5>"
#define HTML_M_END_HEADER_6         "</h6>"

#define HTML_CONTENT_EMBED_START    "<embed src=\""
#define HTML_CONTENT_EMBED_END      "\"/>"

#define HTML_M_START_HYPERLINK      "<a href=\""
#define HTML_M_END_HYPERLINK        "</a>"

#define HTML_START_BOLD 			"<b>"
#define HTML_START_ITALIC			"<em>"
#define HTML_START_HIGHLIGHT        "<mark>"
#define HTML_START_SPOILER			"<span class=\"spoiler\">"
#define HTML_START_STRIKETHROUGH	"<s>"
#define HTML_START_UNDERLINE		"<u>"

#define HTML_END_BOLD 			    "</b>"		
#define HTML_END_ITALIC			    "</em>"
#define HTML_END_MARK               "</mark>"
#define HTML_END_SPOILER			"</span>"
#define HTML_END_STRIKETHROUGH	    "</s>"
#define HTML_END_UNDERLINE		    "</u>"

#define HTML_START_CODE_BLOCK		"<pre><code>"
#define HTML_START_FOOTER			"<footer>"
#define HTML_START_INLINE_CODE		"<code>"
#define HTML_START_PLAIN_TEXT		"<p>"
#define HTML_START_QUOTATION		"<blockquote>"
#define HTML_START_TABLE			"<table>"
#define HTML_START_TABLE_DATA		"<td>"
#define HTML_START_TABLE_ROW		"<tr>"
#define HTML_START_TASK_FINISHED	"<li class=\"task__fin\">"
#define HTML_START_TASK_UNFINISHED	"<li class=\"task_unfin\">"

#define HTML_END_CODE_BLOCK		    "</code></pre>"			
#define HTML_END_FOOTER			    "</footer>"	    
#define HTML_END_INLINE_CODE		"</code>"
#define HTML_END_PLAIN_TEXT		    "</p>"
#define HTML_END_QUOTATION		    "</blockquote>"
#define HTML_END_TABLE			    "</table>"
#define HTML_END_TABLE_DATA		    "</td>"
#define HTML_END_TABLE_ROW		    "</tr>"

#define HTML_START_LIST_ELEMENT		"<li>"
#define HTML_START_ORDERED_LIST		"<ol>"
#define HTML_START_UNORDERED_LIST	"<ul>"

#define HTML_END_LIST_ELEMENT		"</li>"
#define HTML_END_ORDERED_LIST		"</ol>"
#define HTML_END_UNORDERED_LIST	    "</ul>"
